### ISSUE TITLE
有人知道怎么在wsl 中使用吗？

### ISSUE THREAD

**Issue by hjfmailbox** [huan/docker-wechat#106]
执行 curl后并没有反应，是还要安装图形界面吗？

**Comment by Verfolgerle** [comment]
我执行也没反应，我的解决办法是直接把dochat.sh 拉到本地， 再运行就行了

**Comment by hjfmailbox** [comment]
> 我执行也没反应，我的解决办法是直接把dochat.sh 拉到本地， 再运行就行了

多谢，我试试

**Comment by hjfmailbox** [comment]
> > 我执行也没反应，我的解决办法是直接把dochat.sh 拉到本地， 再运行就行了
> 
> 多谢，我试试

改成curl -L https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh | bash 看一下具体的报错信息，对应解决

**Comment by gaelthas** [comment]
运行显示 DoChat Exited with code [0]，请问有没有办法
