### ISSUE TITLE
ubuntu 16.04 上运行提示微信版本过低

### ISSUE THREAD

**Issue by hkd724** [huan/docker-wechat#110]
使用docker命令curl -sL https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh | bash后打开微信提示微信版本过低需要升级，但是又不弹出升级界面，一直卡在登录界面

**Comment by imyhxy** [comment]
同

**Comment by jicki** [comment]
同

**Comment by scottyyf** [comment]
这个是docker里面封装的ｗｘ版本过低，　感觉作者已经没有进行维护了，　上一次提交已经是８个月前？

**Comment by scottyyf** [comment]
还是ＴＸ的问题，网页版不给用，又不做ｌｉｎｕｘ兼容，一天到晚只知道更新农药毒害小学生

**Comment by scottyyf** [comment]
https://hub.docker.com/r/zixia/wechat/tags?page=1&ordering=last_updated

**Comment by zjiek327** [comment]
+1

**Comment by zjiek327** [comment]
ubuntu1804  +1

**Comment by BruceXSK** [comment]
Same problem on ubuntu18.04

**Comment by owen-gxz** [comment]
Same problem on ubuntu20.04

**Comment by jicki** [comment]
> 首先，表示感谢， 然后我装了好久 结果。。。提示版本过低

=0=  已经自己重新弄了一个

https://github.com/jicki/docker-wechat

测试一下吧

**Comment by adrianous** [comment]
> > 首先，表示感谢， 然后我装了好久 结果。。。提示版本过低
> 
> =0= 已经自己重新弄了一个
> 
> https://github.com/jicki/docker-wechat
> 
> 测试一下吧

谢谢，我有时间看一下，对于Docker 刚开始了解 哈哈哈

**Comment by huan** [comment]
Merge to #131
