### ISSUE TITLE
DoChat failed to start after system reboot

### ISSUE THREAD

**Issue by wlnirvana** [huan/docker-wechat#111]
Ubuntu 20.04. DoChat occasionally fails to start after system reboot. Removing `HOME/DoChat/Applcation Data/Tencent/WeChat/All Users/config/configEx.ini` directory resolves the issue.

**Comment by huan** [comment]
Thank you very much for submitting this issue and provide PR for fixing it!

Could you please share the `configEx.ini` content by posting it to this issue so that we can learn more from this case?

It would be more helpful if you can post the `before` and `after` so that we can get more details about it!

**Comment by wlnirvana** [comment]
There is no official doc from the WeChat team regarding how this file works, but I managed to collect the following clues:

- On a clean installation of DoChat, this file does not exist. Nor is it generated immediately. It is only produced after some time of running, which I believe means that it is not essential for starting DoChat (or I guess in general WeChat on Windows).
- Googling "微信 configex.ini" suggests misconfiguration (not necessarily by user, but could be by WeChat itself, maybe during update) in this file could lead to WeChat not able to run on Windows 10.
- [A zhihu user reported](https://www.zhihu.com/question/346319087/answer/1186158991) a similar issue to Tencent and got a call back. He/she resolves it by delete this same file, but did not explicitly say if this was done following Tencent's support instructions.
- The wechat package for Arch Linux seems to delete this file as well. See countstarlight/deepin-wine-wechat-arch#1 Though I have not been able to locate the exactly line to handle this.

**Comment by huan** [comment]
Thank you very much for providing these reference links, they are very valuable because it can help us keep understanding what files do what in the future!

Have a good day, and I hope your update can help our DoChat to be more robust in the next version.
