### ISSUE TITLE
Ubuntu 20.04.1 提示版本过低

### ISSUE THREAD

**Issue by jacksonbean** [huan/docker-wechat#122]
Ubuntu 20.04.1 提示版本过低

**Comment by jacksonbean** [comment]
![image](https://user-images.githubusercontent.com/57471647/112248340-b8e31080-8c90-11eb-9b1a-b6015aaef95f.png)

**Comment by netxiaobai** [comment]
fedora也一样，扫码能同步自己投降，手机点击登陆后弹出“版本过低”点击确定或取消后回到二维码界面。
版本如下：
```shell
NAME=Fedora
VERSION="33 (Workstation Edition)"
```

```shell
[DoChat] 盒装微信 v0.10.22
[DoChat] WeChat 2.9.0.114
[DoChat] Starting...
[DoChat] WeChat.exe exited

**Comment by Lucky-H6** [comment]
盒装微信打包的最高微信版本是2.9, 但是PC微信大版本号已经更新到3了. 希望盒装微信能更新一波新版本~

**Comment by Lucas-Wye** [comment]
> 盒装微信打包的最高微信版本是2.9, 但是PC微信大版本号已经更新到3了. 希望盒装微信能更新一波新版本~

附议

**Comment by huan** [comment]
Merge to #131
