### ISSUE TITLE
2.7 提示更新 2.9 闪退

### ISSUE THREAD

**Issue by liu95-maker** [huan/docker-wechat#123]
[0325/101652:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  652
  Current serial number in output stream:  651
[DoChat] WeChat.exe exit with code 0
[DoChat] Found new version?
[DoChat] WeChat.exe exited

**Comment by huan** [comment]
merge to #131
