### ISSUE TITLE
盒装微信打包的最高微信版本是2.9, 但是PC微信大版本号已经更新到3了. 希望盒装微信能更新一波新版本~

### ISSUE THREAD

**Issue by Lucas-Wye** [huan/docker-wechat#129]
盒装微信打包的最高微信版本是2.9, 但是PC微信大版本号已经更新到3了. 希望盒装微信能更新一波新版本~

_Originally posted by @Lucky-H6 in https://github.com/huan/docker-wechat/issues/122#issuecomment-809945372_

**Comment by SuperBruceJia** [comment]
+1

**Comment by CaoDonghui123** [comment]
+1

**Comment by ouonet** [comment]
+1

**Comment by huan** [comment]
Merge to #131
