### ISSUE TITLE
mkdir: 无法创建目录 “/home/user/.wine/drive_c/users/user/Application Data/Tencent”: 权限不够

### ISSUE THREAD

**Issue by AlightYoung** [huan/docker-wechat#159]
执行安装脚本（`sudo curl -sL https://gitee.com/mirrors/dochat/raw/main/dochat.sh | bash`）出现
``` shell
mkdir: 无法创建目录 “/home/user/.wine/drive_c/users/user/Application Data/Tencent”: 权限不够
```
切换至root用户执行也是这个结果

OS: Debian 11

**Comment by AlightYoung** [comment]
wget下载脚本修改user为本地用户名，问题解决。

**Comment by shuangfu** [comment]
> 

您好，dochat.sh 已经下载打开了，但确实不知道怎么改，文件内有五处出现"user"字符串，请问是都替换成我自己的用户名吗？

**Comment by AlightYoung** [comment]
> > 
> 
> 您好，dochat.sh 已经下载打开了，但确实不知道怎么改，文件内有五处出现"user"字符串，请问是都替换成我自己的用户名吗？
准确来说就是把一些错误路径（user处的用户名）换成自己的user用户名。

**Comment by AlightYoung** [comment]
> > 
> 
> 您好，dochat.sh 已经下载打开了，但确实不知道怎么改，文件内有五处出现"user"字符串，请问是都替换成我自己的用户名吗？

![image](https://user-images.githubusercontent.com/39412759/156692224-49e848f4-0ae5-4bf7-ab51-cfb659c0a88e.png)
例如此处

**Comment by khewweifeng** [comment]
> 

我跟着改，不行 。。。变成被拒绝访问 

试了 `sudo -i` `sudo su` 都得到一样的提示

**Comment by itstartstosnow** [comment]
> > > > 
> > > 
> > > 
> > > 您好，dochat.sh 已经下载打开了，但确实不知道怎么改，文件内有五处出现"user"字符串，请问是都替换成我自己的用户名吗？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/39412759/156692224-49e848f4-0ae5-4bf7-ab51-cfb659c0a88e.png) 例如此处
> 
> 你好，
> 
> 我跟着改，不行 。。。变成被拒绝访问
> 
> 试了 `sudo -i` `sudo su` 都得到一样的提示

我是一口气改了 docker run 后面这两行的三处，运行成功了，供参考：
```
-v "$HOME/DoChat/WeChat Files/":'/home/<yourname>/WeChat Files/' \
-v "$HOME/DoChat/Applcation Data":'/home/<yourname>/.wine/drive_c/users/<yourname>/Application Data/' \
```

**Comment by zlianzhuang** [comment]
只需要改 /home/user 改成自己的就可以
