### ISSUE TITLE
托盘上没有微信图标，关掉微信窗口后无法打开

### ISSUE THREAD

**Issue by ysun46** [huan/docker-wechat#160]
OS: ubuntu 21.10
dochat: zixia/wechat:3.3.0.115

打开微信之后，托盘上图标不见了，导致，如果关闭微信窗口后（点击x按钮，或者ESC），微信还在运行，就是无法弹出窗口。
有什么解决方法吗？

快捷键也试过了，好像也不工作。

**Comment by g0ne150** [comment]
+1 这个怎么办呢？
