### ISSUE TITLE
mkdir: 无法创建目录 “/home/user/.wine/drive_c/users/user/Application Data/Tencent”: 权限不够

### ISSUE THREAD

**Issue by yjacks** [huan/docker-wechat#165]
[DoChat] 盒装微信 v0.14.4
Disabling patch for /home/user/.wine/drive_c/users/user/AppData/Roaming/Tencent/WeChat ...
Disabling patch for /home/user/.wine/drive_c/users/user/Application Data/Tencent/WeChat ...
mkdir: 无法创建目录 “/home/user/.wine/drive_c/users/user/Application Data/Tencent”: 权限不够
使用普通账户

**Comment by yjacks** [comment]
解决方案:将HOME下的DOCHAT文件夹权限设置为777

**Comment by cacacai** [comment]
应该是你没有把当前用户加入到docker组，所以你得yongsudo去启动docker脚本，然后你就得要权限去访问和创建其他目录

**Comment by zhtroy** [comment]
> 解决方案:将HOME下的DOCHAT文件夹权限设置为777

遇到同样的问题，请问这个文件夹的路径是什么？

**Comment by yjacks** [comment]
> > 解决方案:将HOME下的DOCHAT文件夹权限设置为777
> 
> 遇到同样的问题，请问这个文件夹的路径是什么？

就在用户主目录下

**Comment by nathanatgit** [comment]
sh中99行和100行路径写成了固定路径:
/home/user/.wine/drive_c/users/user/Application Data/

所以下把curl到本地之后改一下，把/home/user/里面的user改称你的用户名

**Comment by stingshen** [comment]
> 所以下把curl到本地之后改一下，把/home/user/里面的user改称你的用户名

这么做会让微信无法持久化数据。

在宿主机上，把 ~/DoChat 改成 777 就好了

**Comment by etoyz** [comment]
根据[Docker官方文档](https://docs.docker.com/engine/reference/commandline/run/#volume)：

`-v`用于挂载持久化卷，当宿主机对应目录不存在时，docker会自动创建

>When the host directory of a bind-mounted volume doesn’t exist, Docker automatically creates this directory on the host for you.

然而某些情况下，docker自动创建的目录的owner为root（经过我的多次实验，以非root用户加入docker用户组执行docker run命令，也会导致自动创建的目录的owner为root），因此建议不要依赖docker自动创建目录特性，可以先行创建好这些目录

---
或者直接执行该命令：
`sudo chown $USER $HOME/DoChat -R`
