### ISSUE TITLE
使用脚本安装报错

### ISSUE THREAD

**Issue by whtrys** [huan/docker-wechat#168]
`Disabling patch for /home/user/.wine/drive_c/users/user/AppData/Roaming/Tencent/WeChat ...
Disabling patch for /home/user/.wine/drive_c/users/user/Application Data/Tencent/WeChat ...
mkdir: 无法创建目录 “/home/user/.wine/drive_c/users/user/Application Data/Tencent”: 权限不够`
我明明已经在root下了

**Comment by whtrys** [comment]
切换到普通用户下，尝试 #165 无用，因为用户目录下没有dochat文件/文件夹

**Comment by stingshen** [comment]
> 切换到普通用户下，尝试 #165 无用，因为用户目录下没有dochat文件/文件夹

你是用什么用户和命令执行 `dochat.sh` 的？

**Comment by whtrys** [comment]
普通用户运行了一遍，在报权限不够后，切到root下再运行了一遍

**Comment by stingshen** [comment]
貌似不能用 root 运行，因为：

https://github.com/huan/docker-wechat#attention

建议删除 `$HOME/DoChat/` 后，用普通用户：

1. mkdir -p "$HOME/DoChat/WeChat Files" "$HOME/DoChat/Applcation Data"
2. bash dochat.sh

**Comment by whtrys** [comment]
好的
