### ISSUE TITLE
添加docker用户组后，运行

### ISSUE THREAD

**Issue by yil3** [huan/docker-wechat#172]
[DoChat] 盒装微信 v0.15.0
Disabling patch for /home/user/.wine/drive_c/users/user/AppData/Roaming/Tencent/WeChat ...
Disabling patch for /home/user/.wine/drive_c/users/user/Application Data/Tencent/WeChat ...
mkdir: 无法创建目录 “/home/user/.wine/drive_c/users/user/Application Data/Tencent”: 权限不够

为啥会出现权限不够呀

**Comment by shink** [comment]
同样的问题，用户已经添加到了 docker group，并且 reboot 过了

**Comment by ChisBread** [comment]
Because when docker run, the directory $HOME/DoChat that does not exist is created as root
Run:
```bash
sudo chown -R $USER:$USER $HOME/DoChat
````

**Comment by shink** [comment]
@ChisBread 
Thank you very much. It worked!
But the script exits with code `[0]` after running the command.

```
🚀 Pulling the docker image done.
WARNING: you should run this program as super-user.
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
🚀 Starting DoChat /dɑɑˈtʃæt/ ...

[DoChat] 盒装微信 v0.14.4
Disabling patch for /home/user/.wine/drive_c/users/user/AppData/Roaming/Tencent/WeChat ...
Disabling patch for /home/user/.wine/drive_c/users/user/Application Data/Tencent/WeChat ...
[DoChat] WeChat 3.3.0.115
[DoChat] Starting...
[DoChat] WeChat.exe exit with code 0
[DoChat] Found new version?
[DoChat] WeChat.exe exited


📦 DoChat Exited with code [0]

🐞 Bug Report: https://github.com/huan/docker-wechat/issues
```

Do you know why it happened? Thank you very much!

**Comment by 0FoolishProgrammer** [comment]
I have the same question. Do you know why? thank you very much!
