### ISSUE TITLE
📦 DoChat Exited with code [0]

### ISSUE THREAD

**Issue by rhuang10** [huan/docker-wechat#174]
[DoChat] 盒装微信 v0.14.4
Disabling patch for /home/user/.wine/drive_c/users/user/AppData/Roaming/Tencent/WeChat ...
Disabling patch for /home/user/.wine/drive_c/users/user/Application Data/Tencent/WeChat ...
[DoChat] WeChat 3.3.0.115
[DoChat] Starting...
[DoChat] WeChat.exe exit with code 0
[DoChat] Found new version?
[DoChat] WeChat.exe exited

**Comment by rhuang10** [comment]
duplicated.

**Comment by jankin-z** [comment]
我遇到了同样的问题
