### ISSUE TITLE
Permissions denied

### ISSUE THREAD

**Issue by khewweifeng** [huan/docker-wechat#181]
Tried both command still same result (permissions denied) 

`curl -sL https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh | bash`

`curl -sL https://gitee.com/mirrors/dochat/raw/main/dochat.sh | bash`

result as below 

$ sudo curl -sL https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh | bash

       ____         ____ _           _
      |  _ \  ___  / ___| |__   __ _| |_
      | | | |/ _ \| |   | '_ \ / _` | __|
      | |_| | (_) | |___| | | | (_| | |_
      |____/ \___/ \____|_| |_|\__,_|\__|

      https://github.com/huan/docker-wechat

                +--------------+
               /|             /|
              / |            / |
             *--+-----------*  |
             |  |           |  |
             |  |   盒装    |  |
             |  |   微信    |  |
             |  +-----------+--+
             | /            | /
             |/             |/
             *--------------*

      DoChat /dɑɑˈtʃæt/ (Docker-weChat) is:

      📦 a Docker image
      🤐 for running PC Windows WeChat
      💻 on your Linux desktop
      💖 by one-line of command

🚀 Pulling the docker image...

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=zixia%2Fwechat&tag=3.3.0.115": dial unix /var/run/docker.sock: connect: permission denied
kurinorton@poro:~
$ curl -sL https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh | bash

       ____         ____ _           _
      |  _ \  ___  / ___| |__   __ _| |_
      | | | |/ _ \| |   | '_ \ / _` | __|
      | |_| | (_) | |___| | | | (_| | |_
      |____/ \___/ \____|_| |_|\__,_|\__|

      https://github.com/huan/docker-wechat

                +--------------+
               /|             /|
              / |            / |
             *--+-----------*  |
             |  |           |  |
             |  |   盒装    |  |
             |  |   微信    |  |
             |  +-----------+--+
             | /            | /
             |/             |/
             *--------------*

      DoChat /dɑɑˈtʃæt/ (Docker-weChat) is:

      📦 a Docker image
      🤐 for running PC Windows WeChat
      💻 on your Linux desktop
      💖 by one-line of command

🚀 Pulling the docker image...

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=zixia%2Fwechat&tag=3.3.0.115": dial unix /var/run/docker.sock: connect: permission denied
kurinorton@poro:~
$ curl -sL https://gitee.com/mirrors/dochat/raw/main/dochat.sh | bash

       ____         ____ _           _
      |  _ \  ___  / ___| |__   __ _| |_
      | | | |/ _ \| |   | '_ \ / _` | __|
      | |_| | (_) | |___| | | | (_| | |_
      |____/ \___/ \____|_| |_|\__,_|\__|

      https://github.com/huan/docker-wechat

                +--------------+
               /|             /|
              / |            / |
             *--+-----------*  |
             |  |           |  |
             |  |   盒装    |  |
             |  |   微信    |  |
             |  +-----------+--+
             | /            | /
             |/             |/
             *--------------*

      DoChat /dɑɑˈtʃæt/ (Docker-weChat) is:

      📦 a Docker image
      🤐 for running PC Windows WeChat
      💻 on your Linux desktop
      💖 by one-line of command

🚀 Pulling the docker image...

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=zixia%2Fwechat&tag=3.3.0.115": dial unix /var/run/docker.sock: connect: permission denied

**Comment by khewweifeng** [comment]
OS details as below

neofetch
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMM   kurinorton@poro 
MMMMMMMMMMNs..yMMMMMMMMMMMMMm: +NMMMMMMM   --------------- 
MMMMMMMMMN+    :mMMMMMMMMMNo` -dMMMMMMMM   OS: MX x86_64 
MMMMMMMMMMMs.   `oNMMMMMMh- `sNMMMMMMMMM   Host: K43SD 1.0 
MMMMMMMMMMMMN/    -hMMMN+  :dMMMMMMMMMMM   Kernel: 5.10.0-16-amd64 
MMMMMMMMMMMMMMh-    +ms. .sMMMMMMMMMMMMM   Uptime: 35 mins 
MMMMMMMMMMMMMMMN+`   `  +NMMMMMMMMMMMMMM   Packages: 2198 (dpkg), 13 (flatpak) 
MMMMMMMMMMMMMMNMMd:    .dMMMMMMMMMMMMMMM   Shell: bash 5.1.4 
MMMMMMMMMMMMm/-hMd-     `sNMMMMMMMMMMMMM   Resolution: 1280x1024 
MMMMMMMMMMNo`   -` :h/    -dMMMMMMMMMMMM   DE: Xfce 4.16 
MMMMMMMMMd:       /NMMh-   `+NMMMMMMMMMM   WM: Xfwm4 
MMMMMMMNo`         :mMMN+`   `-hMMMMMMMM   WM Theme: mx-comfort 
MMMMMMh.            `oNMMd:    `/mMMMMMM   Theme: Adwaita-dark [GTK2/3] 
MMMMm/                -hMd-      `sNMMMM   Icons: Papirus-mxblue-darkpanes [GTK2], Adwaita [GTK3] 
MMNs`                   -          :dMMM   Terminal: xfce4-terminal 
Mm:                                 `oMM   Terminal Font: Liberation Mono 11 
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM   CPU: Intel i5-2450M (4) @ 3.100GHz 
                                           GPU: NVIDIA NVIDIA Corporation GeForce GT 610M 
                                           GPU: Intel 2nd Generation Core Processor Family 
                                           Memory: 1582MiB / 5842MiB

**Comment by khewweifeng** [comment]
![image](https://user-images.githubusercontent.com/54496743/178149206-f61f17ad-81e5-4ab9-bdf7-02dd30fbef49.png)

OS details

**Comment by khewweifeng** [comment]
Found the solution = https://github.com/huan/docker-wechat/issues/55#issuecomment-648545331

**Comment by WendaoLee** [comment]
This is the permission problem.You can use
```
sudo gpasswd -a $USER docker
```
to add your user to the group `docker` so you can have permission to use `docker pull`.
The other resolution is to to download `dochat.sh` and run it with `sudo` in your current machine.
