### ISSUE TITLE
DoChat在Fedora上无法使用

### ISSUE THREAD

**Issue by hehellooedas** [huan/docker-wechat#192]
![image](https://user-images.githubusercontent.com/96963528/217807510-828450ca-62fd-451a-ac5d-fa23a8050c9a.png)

![image](https://user-images.githubusercontent.com/96963528/217807621-e81050a9-eda6-4c1f-9451-d557e78b0ad8.png)

已经把当前用户加入到docker组，并且安装了nvidia-container-toolkit.
非root用户手动创建DoChat文件并且把docker.sh里user改为$USER后仍旧提示没有权限。
![image](https://user-images.githubusercontent.com/96963528/217808192-00715f0c-6efe-4993-a273-6d6e5d660de4.png)

运行脚本后会出现这个界面，点击确定或者关闭后报错。

**Comment by huan** [comment]
Could you please share what you have done for fixing it?

**Comment by hehellooedas** [comment]
![image](https://user-images.githubusercontent.com/96963528/218016617-ac7669f9-b3e1-4701-9d8b-92933e703c8e.png)


`sudo usermod -aG docker $USER`

`curl -sL https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh | bash`

It will pull the docker-image "zixia/wechat" automaticaly.
It will also create the directory "DoChat",but it belongs to root.

`sudo chown $USER:$USER DoChat -R`

`curl -sL https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh | bash`
Run it again.

The WeChat will appear but it also has some problems.For example,it cannot follow system agent automatically and The terminal still prompts an error and the container cannot be saved(That means it becomes a one-time WeChat).
