### ISSUE TITLE
【问题】文件映射老是不正确

### ISSUE THREAD

**Issue by alex-oos** [huan/docker-wechat#207]
`   docker run \
        --name DoChat \
        --rm \
        -i \
        \
        -v "/data2/DoChat/WeChatFiles/":'/home/user/file/' \
        -v "/data2/DoChat/ApplicationData/":'/home/user/.wine/drive_c/users/user/ApplicationData/' \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        \
        -e DISPLAY \
        \
        -e XMODIFIERS=@im=fcitx \
        -e GTK_IM_MODULE=fcitx \
        -e QT_IM_MODULE=fcitx \
        -e GID="$(id -g)" \
        -e UID="$(id -u)" \
        \
        --ipc=host \
        --privileged \
        \
        zixia/wechat`
 
这是我的启动命令，我用微信保存文件，在电脑上 /data2/DoChat/WeChatFiles/ 或 "/data2/DoChat/ApplicationData/ 目录下总是找不见文件

**Comment by thenamehasbeentake** [comment]
https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag

**Comment by alex-oos** [comment]
> https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag

好的，谢谢了，

**Comment by alex-oos** [comment]
我的问题解决了，终于修改为如下
`docker run \
  --name wechat \
  --rm \
  -i \
  \
  -v "$HOME/wechat/WeChatFiles/":'/home/user/WeChatFiles/' \
  -v "$HOME/wechat/ApplcationData":'/home/user/.wine/drive_c/users/user/ApplicationData/' \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  \
  -e DISPLAY \
  \
  -e XMODIFIERS=@im=fcitx \
  -e GTK_IM_MODULE=fcitx \
  -e QT_IM_MODULE=fcitx \
  -e GID="$(id -g)" \
  -e UID="$(id -u)" \
  \
  --ipc=host \
  --privileged \
  \
  zixia/wechat
`

作者: 快乐小王子🥝
链接: https://alex-oos.github.io/posts/6da36a09/#%E4%B8%80%E3%80%81docker-wechat-%EF%BC%88%E7%9B%AE%E5%89%8D%E5%8F%AF%E7%94%A8%EF%BC%8C%E5%BE%AE%E4%BF%A1%E7%89%88%E6%9C%AC-3-3-0%EF%BC%89
来源: 快乐小王子🥝
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。`
