### ISSUE TITLE
The proportion of the docker-wechat is too small

### ISSUE THREAD

**Issue by lindamustang** [huan/docker-wechat#36]
![2020-03-11 15-59-50 的屏幕截图](https://user-images.githubusercontent.com/50109983/76397623-605b1100-63b6-11ea-995b-3a85ac99b22e.png)
It costs me so much time, but I still don`t know why.

**Comment by huan** [comment]
To enlarge the window & fonts size, try:

```sh
curl -sL https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh \
  | DOCHAT_DPI=192 bash
```

**Comment by lindamustang** [comment]
Sorry, it my fault not read  the README carefully.

**Comment by huan** [comment]
You are welcome.
