### ISSUE TITLE
[Problem] The DOCHAT_DPI do not work on VERSION=2.7.1.85

### ISSUE THREAD

**Issue by mengzyou** [huan/docker-wechat#41]
## Description

Whatever the value of `DOCHAT_DPI` set, there is no change for the UI. See below picture, I set `DOCHAT_DPI= 144`, the display is not clear.  

![image](https://user-images.githubusercontent.com/360603/78003695-a8dd6d00-736b-11ea-884b-7aad2a0d8db2.png)

## APP & OS Version

VERSION=2.7.1.85

NAME="openSUSE Leap"
VERSION="15.1"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.1"

## More Info

Tried VERSION=2.8.0.121, this is no DPI problem, but has other problems.

**Comment by huan** [comment]
![image](https://user-images.githubusercontent.com/1361891/78012107-16db6180-7377-11ea-82b1-995d388ad78c.png)

I'm using the 2.7.1.85 right now, and it seems the DPI works without any problem for me (Ubuntu 19.10).

So it might be related to an OpenSUSE distribution problem?

**Comment by mengzyou** [comment]
It's strange, the VERSION=2.8.0 is working fine with DPI, so I'm not sure what's wrong about this.

**Comment by mengzyou** [comment]
@huan Hi, Huan, the `latest` tag image was working fine for me when I post issue https://github.com/huan/docker-wechat/issues/16. But now, I updated to current `latest` image, and encounter some problems. I can't find back the image at that time. Could you help me confirm which tag image on that time?

**Comment by huan** [comment]
The `latest` tag will be always updated when I push new commits to this repository.

Please go to <https://hub.docker.com/r/zixia/wechat/tags> and select a specific tag to make it more predictable.

**Comment by mengzyou** [comment]
```
2.7.1.85
docker pull zixia/wechat:2.7.1.85
Last updateda month ago
```

So, I just can find this image taged, and face this DPI problem.

**Comment by huan** [comment]
I'm using this version too, and everything works like a charm.

**Comment by mengzyou** [comment]
Ok, I find the working image now, the version is 2.8.0.112, the DPI works fine and there is no issue mentioned on https://github.com/huan/docker-wechat/issues/40 .

I think we can close this issue now.

**Comment by huan** [comment]
Glad to know that, cheers!
