### ISSUE TITLE
Cannot run latest wechat with docker

### ISSUE THREAD

**Issue by shuming1008** [huan/docker-wechat#48]
I tried to run wechat with latest docker image, but failed.
```
 $ docker run zixia/wechat
[DoChat] 盒装微信 v0.10.4
[DoChat] WeChat 2.7.1.88
[DoChat] Starting...
[DoChat] Found new version
[DoChat] WeChat.exe exited
```
The environment is: Ubuntu 18.04

**Comment by Declarcall** [comment]
me too ..
https://github.com/huan/docker-wechat/issues/29#issuecomment-619442169

**Comment by huan** [comment]
Merge to #29

**Comment by shuming1008** [comment]
Hi Huan,

    RESTART doesn't solve the problem...
    The issue should be re-opened.

    Do you have any other approach?

    Thanks!

**Comment by huan** [comment]
This issue is duplicated with #29 and please visit #29 for future information.

If you believe it should not be merged, please let me know what you think. Thanks.
