### ISSUE TITLE
报错exec user process caused "exec format error"

### ISSUE THREAD

**Issue by 66Leo66** [huan/docker-wechat#49]
硬件：Nvidia Jetson Nano
系统：Ubuntu 18.04 LTS
架构：Arm64
输出：
```
nano@jetsonnano:~/Desktop$ sudo bash dochat.sh 

       ____         ____ _           _
      |  _ \  ___  / ___| |__   __ _| |_
      | | | |/ _ \| |   | '_ \ / _` | __|
      | |_| | (_) | |___| | | | (_| | |_
      |____/ \___/ \____|_| |_|\__,_|\__|

      https://github.com/huan/docker-wechat

                +--------------+
               /|             /|
              / |            / |
             *--+-----------*  |
             |  |           |  |
             |  |   盒装    |  |
             |  |   微信    |  |
             |  +-----------+--+
             | /            | /
             |/             |/
             *--------------*

      DoChat /dɑɑˈtʃæt/ (Docker-weChat) is:

      📦 a Docker image
      🤐 for running PC Windows WeChat
      💻 on your Linux desktop
      💖 by one-line of command

🚀 Pulling the docker image...

2.7.1.85: Pulling from zixia/wechat
Digest: sha256:e6e9d21c7cd1dfae0484e697f12f5f3c401de2f02e771d061868740e0d26549d
Status: Image is up to date for zixia/wechat:2.7.1.85
docker.io/zixia/wechat:2.7.1.85

🚀 Pulling the docker image done.
🚀 Starting DoChat /dɑɑˈtʃæt/ ...

standard_init_linux.go:211: exec user process caused "exec format error"
```
![DoChatCannotRun](https://user-images.githubusercontent.com/33322229/80296778-5a778e80-87b0-11ea-921f-83bacd7a4c2e.png)

**Comment by huan** [comment]
I'm afraid that we are not supporting the `Arm` architecture right now, and it seems can not be supported in the near future.

Because all our binaries are x86 which is not compatible with ARM.

**Comment by daranday** [comment]
Hi @huan, I would really love to use wechat docker on my Raspberry Pi to run it on my TV. I wonder if we have sources for those binaries so that they can be cross-compiled to ARM architecture? Thanks!

**Comment by huan** [comment]
Hi @daranday ,

Thanks for sharing your thoughts. We have no source of the windows WeChat and even if we have I'm afraid that we can not build it on raspberry pi.

Please feel free to read the source and let me know if you can find any solutions because I'd like to support it on raspberry pi too.

**Comment by linrol** [comment]
> Hi @huan, I would really love to use wechat docker on my Raspberry Pi to run it on my TV. I wonder if we have sources for those binaries so that they can be cross-compiled to ARM architecture? I can contribute to generate them if that's the case. Thanks!

基于ARM架构适配的box86+wine实现docker微信机器人，欢迎大佬们参考：
https://blog.linrol.cn/archives/1703220186416
