### ISSUE TITLE
昨天用了一下最新版的docker镜像立马微信就被封了

### ISSUE THREAD

**Issue by ltkun** [huan/docker-wechat#55]
说我 限制登录不可解封 使用了微信外挂 非官方客户端或模拟器 关键不可解封太恶心了

**Comment by huan** [comment]
The WeChat client in our docker is definitely the official WeChat client!

**Comment by ltkun** [comment]
说明腾讯有手段侦测出用了模拟器啊

**Comment by huan** [comment]
I'm sorry to hear that.

DoChat is not run inside a simulator, we are using the Wine project.

**Comment by ltkun** [comment]
sorry 我半夜才醒悟了被封的微信号不是昨天登录的那个账号！然后因为时间上非常接近我就以为是在Linux上登录了才导致被封的，其实是我记岔了，万分抱歉！关键被封的那个啥事情也没有干就被封了...

**Comment by huan** [comment]
Glad to know that you are safe with our DoChat!

**Comment by e7** [comment]
中英交流have come have go

**Comment by Jakiejjj** [comment]
I see a lot of native Chinese speaker communicate with other Chinese in English.But why？

**Comment by sheepduke** [comment]
> I see a lot of native Chinese speakers communicate with other Chinese in English.But why？

Because this is a international platform and there might be Non-Chinese audience.

It is considered impolite if a group of people keep talking in a language that only they can understand. ;-)

And considering the fact that English may be understood by most people here, so...

**Comment by shaodan** [comment]
> I see a lot of native Chinese speakers communicate with other Chinese in English.But why？

There maybe another reason that one doesn't have Chinese input method on his/her computer :P

**Comment by jorschach-g** [comment]
Like... ibus is usable... But one would definitely consider that to be a lot of work changing it when both parties can understand the information.

**Comment by ShiqiMeng** [comment]
So 优秀 !

**Comment by yusiwen** [comment]
So, it's safe to run wechat in docker after all of this? Is it a false alarm?

**Comment by ltkun** [comment]
Yes, it's absolutely safe.

在 2020年6月14日星期日，Siwen Yu <notifications@github.com> 写道：

**Comment by ShiqiMeng** [comment]
Ubuntu 18.04
$sudo curl -sL https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh | bash

I have problem as follow:

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=zixia%2Fwechat&tag=2.7.1.85: dial unix /var/run/docker.sock: connect: permission denied

**Comment by dongdong4fei** [comment]
> Ubuntu 18.04
> $sudo curl -sL https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh | bash
> 
> I have problem as follow:
> 
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=zixia%2Fwechat&tag=2.7.1.85: dial unix /var/run/docker.sock: connect: permission denied

You may try this solution:
https://www.cnblogs.com/informatics/p/8276172.html

**Comment by Insua** [comment]
我靠 是zixia大佬吗 用月光宝盒穿梭了好多年啊

**Comment by Faniche** [comment]
> > I see a lot of native Chinese speakers communicate with other Chinese in English.But why？
> 
> There maybe another reason that one doesn't have Chinese input method on his/her computer :P

I have found the solution.
First, install the ubuntu with 'Chinese' version, the default Chinese input method is very good now;
Second, change system language to english, when you restart the system, gnome will notify you whether change the directories in home folder to English. Set it to english permently.
And enjoy it. No Sogou or ancient google pinyin.
I don't know if the soletion works in other distros or not, it works perfect in ubuntu.

**Comment by sheepduke** [comment]
On 2020-07-03 07:18, Faniche <notifications@github.com> wrote:
>> > I see a lot of native Chinese speakers communicate with other Chinese in English.But why？
>> 
>> There maybe another reason that one doesn't have Chinese input method on his/her computer :P
>
> I have found the solution.
> First, install the ubuntu with 'Chinese' version, the default Chinese input method is very good now;
> Second, change system language to english, when you restart the system, gnome will notify you whether change the directories in home folder to English. Set it to english permently.
> And enjoy it. No Sogou or ancient google pinyin.
> I don't know if the soletion works in other distros or not, it works perfect in ubuntu.
>
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/huan/docker-wechat/issues/55#issuecomment-653569955

Referring input method, I highly recommend Rime framework.

It in fact supports all platforms (not sure about iOS). You could get
identical experiences among them.

There is a learning curve of course. But it is not that hard IMHO.

And this is my Rime configurations for Wubi 86/98 and Flypy:

https://github.com/sheepduke/rime-wubi
https://github.com/sheepduke/rime-flypy

Hope that helps.

**Comment by jorschach-g** [comment]
On that note... iOS is just not helpful in that manner... And rime itself
is just less than moderately unhelpful as always in most of the platforms
without configuration, which is another great hassle...

I really don’t prefer that considering fcitx is in perfect shape when you
are using arch-based system...

**Comment by sheepduke** [comment]
>On that note... iOS is just not helpful in that manner... And rime itself
is just less than moderately unhelpful as always in most of the platforms
without configuration, which is another great hassle...
>
>I really don’t prefer that considering fcitx is in perfect shape when you
are using arch-based system...

True. Rime if very clumsy without configuration. 
And the dictionary is rather weak compared with Sogou etc.

I did not feel it probably because I use Wubi so I do not rely on a personal dictionary ;-)

Anyway, it is simply personal choice. Let's put it to an end. It is already off-topic. :-)

**Comment by linusyoung** [comment]
> Glad to know that you are safe with our DoChat!

so should this issue be closed then??

**Comment by huan** [comment]
@linusyoung Yes, this issue is safe to be closed. Thank you for your attention!

**Comment by efaun** [comment]
> > I see a lot of native Chinese speakers communicate with other Chinese in English.But why？
> 
> Because this is a international platform and there might be Non-Chinese audience.
> 
> It is considered impolite if a group of people keep talking in a language that only they can understand. ;-)
> 
> And considering the fact that English may be understood by most people here, so...

我也有和“Jakiejjj”一样的疑惑，微信只有中国人才用吧，或者大部分用的都是中国人，虽然项目在外国平台上，但使用和维护的不都是中国人吗？所以我认为这是一种文化不自信的表现，多年前爆火的《中国话》，想来真是不值

**Comment by yehaha9876** [comment]
用英语大家累不累。。。。

**Comment by efaun** [comment]
> 用英语大家累不累。。。。

装逼的事情怎么会累呢，管他外国人看不看得懂，语法通不通顺😅

**Comment by efaun** [comment]
> 用英语大家累不累。。。。

装逼的事情怎么会累呢，管他外国人用不用微信，看不看得懂，语法通不通顺😅

**Comment by dolfly** [comment]
haha

**Comment by YYCPro** [comment]
一中文一英语，跨服交流。😂😂😂

**Comment by walk143** [comment]
maybe the Disclaimer of [readme.md](https://github.com/huan/docker-wechat#disclaimer) should be updated?

**Comment by xiaomaitai** [comment]
> > I see a lot of native Chinese speakers communicate with other Chinese in English.But why？
> 
> Because this is a international platform and there might be Non-Chinese audience.
> 
> It is considered impolite if a group of people keep talking in a language that only they can understand. ;-)
> 
> And considering the fact that English may be understood by most people here, so...

In that case, you should use Chinese instead for there are more Chinese speakers in the world than English.

**Comment by sheepduke** [comment]
> > > I see a lot of native Chinese speakers communicate with other Chinese in English.But why？
> > 
> > 
> > Because this is a international platform and there might be Non-Chinese audience.
> > It is considered impolite if a group of people keep talking in a language that only they can understand. ;-)
> > And considering the fact that English may be understood by most people here, so...
> 
> In that case, you should use Chinese instead for there are more Chinese speakers in the world than English.
>
In my humble opinion, your statement is not relevant to what I have said.

I surely admit that there are more *native* Chinese speakers than *native* English speakers. This is truth and I am happy with it. But if you count "people who *can* speak Chinese" vs "people who *can* speak English", I suspect your statement will not stand.

The truth is that English is much more widely adopted (than Chinese) in a business/daily environment. It is a must-learn second language in many countries (China included), so it is more likely to find English speakers in GitHub than Chinese speakers. To make it more understandable, just imagine that you could speak English in many countries and expect people to understand, but you probably do not have the same expectation when speaking Chinese.

I think for many people (including myself) English is just a tool for communication. It is just enough for exchange business/technical ideas. WeChat has some non-Chinese users (though not that much I suppose), so speaking English here makes it possible to help more people. I would not suggest doing so for some Chinese-only projects, for example Rime (a Chinese input method).

These are just *my* opinions. Of course, you could speak whatever you like here. I do not judge it. :-)

**Comment by phui-chen** [comment]
> 中英交流have come have go

你这"有来有回"也挺秀

**Comment by lhttjdr** [comment]
> 中英交流have come have go

same 9 years, why you outstanding
