### ISSUE TITLE
Ubuntu可以正常发送文字，但是在聊天不能显示文字

### ISSUE THREAD

**Issue by anxiang1836** [huan/docker-wechat#57]
就是可以正常输入文字，但是在聊天框中不显示光标，也没有办法显示已经敲进去的文字，但是回车后可以发送那些已经输入进去的文字，烦请问一下，这个问题应该怎么解决呢？谢谢

**Comment by boltomli** [comment]
有旧的版本曾经可以显示（更早一点的2.7
DPI可能也有关系

**Comment by boltomli** [comment]
#40 同样的问题

**Comment by huan** [comment]
Merge to #40
