### ISSUE TITLE
Request for 'Wechat Enterprise' (企业微信)

### ISSUE THREAD

**Issue by c4pt0r** [huan/docker-wechat#8]
Thank you!

**Comment by huan** [comment]
You are welcome and I'm very glad to add WeChat Work support after we can confirm that the individual version of WeChat runs smoothly enough.

Please stay tuned! :sunglasses:

**Comment by huan** [comment]
We have [DoWork /dɑɑˈwɜːk/ 盒装企业微信](https://github.com/huan/docker-wxwork) online today!

See: <https://github.com/huan/docker-wxwork>
