### ISSUE TITLE
输入框看不到光标，也看不到输入的内容

### ISSUE THREAD

**Issue by yangjian102621** [huan/docker-wechat#82]
![image](https://user-images.githubusercontent.com/4746061/88868197-14fcae80-d242-11ea-9cd8-2099535fefc2.png)

我在 Ubuntu 18.04LTS 和 20.04LTS 都试了，同样的问题。

**Comment by huan** [comment]
Have you solved your problem? If so, could you share about your experience with how to fix it in your case so that other users will be able to benefit from your post?

Thank you very much!

**Comment by yangjian102621** [comment]
I did not solve it, i just reset back to wechat:2.7.1.85. it's workers.

**Comment by huan** [comment]
@yangjian102621 Thank you very much for the feedback!
