### ISSUE TITLE
How can I add DoChat to application

### ISSUE THREAD

**Issue by Aoi-hosizora** [huan/docker-wechat#92]
My ubuntu is `20.04`, and I can run DoChat successfully.
I want to add this dochat.sh to application. I use the following `.desktop` file to `/usr/share/applications` and the icon is added but it doesn't work when I click it.

```text
[Desktop Entry]
Version=1.0.0
Name=DoChat
Exec="/home/aoihosizora/software/wechat-docker/dochat.sh"
Icon=
Terminal=false
Type=Application
Categories=Application;Network;Tencent Software;
```

![image](https://user-images.githubusercontent.com/31433480/96423795-68244300-122c-11eb-8db2-6c4e09f7a59f.png)

**Comment by huang8604** [comment]
try   Exec=bash /home/aoihosizora/software/wechat-docker/dochat.sh &

**Comment by Aoi-hosizora** [comment]
Oh sorry for late reply.

I try to change `.../dochat.sh` to `bash .../dochat.sh &` or `bash .../dochat.sh` but the icon disappeared. It seems that I could not write `Exec` like this.

**Comment by Aoi-hosizora** [comment]
@huang8604 I try to modify the first line of `dochat.sh` from `#!/usr/bin/env bash` to `#!/bin/bash` with `Exec=.../dochat.sh`, and the dochat does run successfully!
